name: NASA Project CI
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ master, main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - uses: actions/checkout@v3
      - name: Use Node.js version 20
        # uses: actions/setup-node@v2
        uses: actions/setup-node@v3
        with:
          # node-version: '16'
          node-version: '20'
      - run: npm install
      - run : npm run build --prefix client

  # deploy:
  #   needs: build